name: flutter_practise_user_firebase
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+21

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: 3.3.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.1.0
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  reactive_forms: ^14.2.0
  sprintf: ^7.0.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/png/